### PR TITLE
Rename repository references

### PR DESCRIPTION
**Pull request by terryyylim**
**What this PR does / why we need it**:

The repository has been renamed from `observation-service` to `timber`. This PR updates references to the old repository name.

**Which issue(s) this PR fixes**:

`NONE`

### CODE REVIEW

**Comment by pradithya** [comment]
I think we need to update the [chart name](https://github.com/caraml-dev/timber/blob/bfffb9b7e789dcc392be3f2876e55f29fc7f402b/infra/charts/observation-service/Chart.yaml#L2) too

**Comment by terryyylim** [comment]
>I think we need to update the [chart name](https://github.com/caraml-dev/timber/blob/bfffb9b7e789dcc392be3f2876e55f29fc7f402b/infra/charts/observation-service/Chart.yaml#L2) too

Oh I thought it should stay the same, since there should be dataset-service chart later on as well right?

**Comment by pradithya** [comment]
> > I think we need to update the [chart name](https://github.com/caraml-dev/timber/blob/bfffb9b7e789dcc392be3f2876e55f29fc7f402b/infra/charts/observation-service/Chart.yaml#L2) too
> 
> Oh I thought it should stay the same, since there should be dataset-service chart later on as well right?

I see, make sense. How should we call dataset-service? Timberland? 😄

**Comment by pradithya** [comment]
> > > I think we need to update the [chart name](https://github.com/caraml-dev/timber/blob/bfffb9b7e789dcc392be3f2876e55f29fc7f402b/infra/charts/observation-service/Chart.yaml#L2) too
> > 
> > 
> > Oh I thought it should stay the same, since there should be dataset-service chart later on as well right?
> 
> I see, make sense. How should we call dataset-service? Timberland? 😄

Just to confirm, this repository (timber) contains several component: dataset service, observation service, and log writers.  Each will have separate helm chart correct?

**Comment by terryyylim** [comment]
>Just to confirm, this repository (timber) contains several component: dataset service, observation service, and log writers. Each will have separate helm chart correct?

Yup that is correct!

**Review by pradithya — APPROVED** [review]
Got it! LGTM

**Review by krithika369 — APPROVED** [review]

**Pull request merged**
